#!/bin/bash

# Config
# ======
# Where new podcast episodes can be found
DOWNLOAD_PATH="$HOME/Podcasts"
# Where the player will be mounted
MOUNT_POINT="/media/$USER/ROCKBOX_4G"
# Playlist, also used to detect files deleted on the player
PLAYLIST="$MOUNT_POINT/Playlists/podcasts.m3u"
# Where to put podcasts relative to the MOUNT_POINT
PODCASTS_ROOT="PODCASTS"
# 1K-blocks to keep spare for player operation
ELBOW_ROOM=100

# find and load the implementation
SCRIPT_DIR=$(dirname $(readlink -f $0))
. $SCRIPT_DIR/functions.sh

check_if_mounted
delete_deleted
copy_downloaded
update_playlist
